### PR TITLE
refactor(rpc)!: Rename rollup_getProof to linea_getProof

### PR DESCRIPTION
**Pull request by usmansaleem**
## PR Description
Rename `rollup_getProof` to `linea_getProof`.
## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by macfarla — APPROVED** [review]

**Review by matkt — APPROVED** [review]
LGTM

**Comment by jpnovais** [comment]
Hi, I think that just renaming the method is an forced breaking chance and this will cause unnecessary disruption to our partners. I suggest to:
-  this Shomei version have both methods working `linea_getProof` and `rollup_getProof` (easy to achieve and code reused)
- deploy and notify partners to migrate to `linea_getProof`
- once migrated, make new release that only has new method.

@julien-marchand WDYT?

**Comment by julien-marchand** [comment]
@jpnovais this endpoint is not yet used by external partners. The goal [of this task](https://github.com/Consensys/protocol-misc/issues/885) is specifically to rename it to something more coherent before it's made available publicly

**Comment by julien-marchand** [comment]
@usmansaleem @macfarla @matkt We plan to release the mainnet feature in ~10 days. Can we cut a release out of this, to rename it in the client part? Except if you want to package other changes to it in the short-term.

**Comment by matkt** [comment]
no other changes in the short term . I think we can make a release

**Pull request merged**
